### ISSUE TITLE
Practica 6 Ejercicios de Hilos en Consola 

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/practica-de-hilos-abicoronel#2]
[Practica 6_Ejercicios de hilos en consola.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-abicoronel/files/8448904/Practica.6_Ejercicios.de.hilos.en.consola.pdf)

**Comment by SANDRAVELASCO** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
